### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by ghost** [ferno/loco#2]
Thank you for adding the composer.json. It would be great if you could submit this repository to packagist.org too. Before that, version-tagging the repository is important.

**Comment by qntm** [comment]
@codeless Hi there. Some years ago, I used to use the name "ferno" here on GitHub, but I use "qntm" now - accordingly, this repo has been moved from https://github.com/ferno/loco to https://github.com/qntm/loco. However, Loco is still published under the package name `ferno/loco`.

Almost a decade later, I have finally registered on packagist.org. My username there is [qntm](https://packagist.org/users/qntm/), as you would expect. Could you please add me as a maintainer on the `ferno` vendor on Packagist? Thank you in advance.
